### ISSUE TITLE
PoW Reward Spikes

### ISSUE THREAD

**Issue by Nagalim** [bananenwilly/peercoinexplorer.net-charts#5]
PoW reward spikes down to 0 on days when there are no blocks for the day, which messes up the averages and makes the data not as interesting.  Rather, it should be an average of the day before and after it, or at least equal to the day before it.  
Refer to Line 73 in chart_parser/renderToFile.php

:Addendum
Line 91 of renderToFile.php
It may be worth also looking into the handling of pos/pow block ratio for days where that number is infinite, though that's more tricky because:
(A/B + C/D)/2 =/= (A+C)/(B+D)
Which means that when averaging, (day 1 plus day 2 divided by 2) is not the same as (the total average ratio of the data over the two days).  However, when the ratio of both days are the same (A/B=C/D), the two sides become equal to that ratio, so it's not an error you would notice without analysis.

**Comment by Nagalim** [comment]
Only on days where there are no blocks, because the reward clearly isn't actually zero, and it messes up the chart.  If the average is too much, just duplicating the previous day's result will do, though an average of before and after is more technically correct, but has issues when there is no future (i.e. when the last data point is zero, just use the day before).  I hope that's not too complex.
Ex:
Raw Data: (50, 51, 50, 0, 51, 50)
What it should be: (50, 51, 50, 50.5, 51, 50)
What would also work: (50, 51, 50, 50, 51, 50)

**Comment by Nagalim** [comment]
You can see the spikes downward here:

![20210828_084449](https://user-images.githubusercontent.com/12321025/131218323-36ce8f52-cbb7-4ad5-918e-6e58848f71c0.jpg)

**Comment by bananenwilly** [comment]
![grafik](https://user-images.githubusercontent.com/11148913/131220144-6a99c98b-cd11-447d-96bc-660a0c008e6b.png)
before

![grafik](https://user-images.githubusercontent.com/11148913/131220155-a99c57e8-b779-432a-957f-7ae3244d7c85.png)
after

**Comment by bananenwilly** [comment]
https://github.com/bananenwilly/peercoinexplorer.net-charts/commit/6659ad5044fc5ae0e7512ff1840109dd3039256d

closes this
